name: Addition Pull Request
description: Create a pull request to add an item to the list.
title: "[Addition]"
labels: ["Addition"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Pull request will be closed if incomplete. These are required before submitting and by sumbitting you agree that you have done them.
      options:
        - label: I've checked that my mod suggestion hasn't already been added to one of the lists.
          required: true
        - label: I've made sure that my addition is in the same format as the rest of the repo.
          required: true
        - label: I've checked the latest pull requests to make sure that this mod hasn't already been suggested.
          required: true
  - type: textarea
    attributes:
      label: What did you add?
    validations:
      required: true
  - type: input
    attributes:
      label: Dose this PR fix or close any open issues?
      description: "If so, please link them here with Fixes #(issue number) or Closes #(issue number) as relevent. If not, leave blank."
    validations:
      required: false