---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

name: Feature Request
description: Suggest the addition of a mod to the list!
title: "[Feature Request]"
labels: ""
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Issue will be closed if incomplete.
      options:
        - label: I've checked the latest issues to make sure that this hasn't already been suggested.
          required: true
  - type: input
    attributes:
      label: Please describe the problem.
      description: A clear and concise description of what the problem is.
      value: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context.
      description: Keep in mind that you can still insert screenshots below.
