---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

name: Feature Request
description: Suggest the addition of a mod to the list!
title: "[Feature Request]"
labels: ""
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Issue will be closed if incomplete.
      options:
        - label: I've checked the latest issues to make sure that this hasn't already been suggested.
          required: true
  - type: textarea
    attributes:
      label: What is your mod's name?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What is your mod's main version?
      options:
        - 1.8.X or earlier
        - 1.12.X
        - 1.15.X (Forge)
        - 1.15.X (Fabric)
        - 1.16.X (Forge)
        - 1.16.X (Fabric)
        - 1.17.X (Forge)
        - 1.17.X (Fabric)
        - 1.18.X (Forge)
        - 1.18.X (Fabric)
        - Other (Forge)
        - Other (Fabric)
        - Other (Other)
    validations:
      required: true
  - type: input
    attributes:
      label: Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.
    validations:
      required: true
  - type: input
    attributes:
      label: What is your reasoning for including this mod?
  - type: input
    attributes:
      label: (OPTIONAL) Give some extra information about the mod.
