name: Software Addition
description: Suggest the addition of a piece of software to the list!
title: "[Software Addition]"
labels: ["Addition Software"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Issue will be closed if incomplete.
      options:
        - label: I've checked that my software suggestion hasn't already been added to one of the lists.
          required: true
        - label: I've checked the latest issues to make sure that this software hasn't already been suggested.
          required: true
  - type: input
    attributes:
      label: What is your software's name?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What systems do you know your software works on?
      options:
        - label: Windows 11
        - label: Windows 10
        - label: Windows 8/8.1
        - label: Windows 7
        - label: Windows XP or earlier
        - label: MacOS
        - label: Linux
        - label: Other
  - type: input
    attributes:
      label: Input a link to your suggested software.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your reasoning for including this software?
    validations:
      required: true
  - type: input
    attributes:
      label: (OPTIONAL) Give some extra information about the software.

